### ISSUE TITLE
test failure with twisted 18.7.0

### ISSUE THREAD

**Issue by juliantaylor** [warner/foolscap#42]
In debian unstable amd64 with twisted 18.7.0 foolscap currently fails the 
foolscap.test.test_negotiate.Crossfire.test4 test

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/build/foolscap-0.13.1/debian/python-foolscap/usr/lib/python2.7/dist-packages/foolscap/test/test_negotiate.py", line 454, in test4
    rref1 = yield self.connect2()
  File "/build/foolscap-0.13.1/debian/python-foolscap/usr/lib/python2.7/dist-packages/foolscap/test/test_negotiate.py", line 382, in connect2
    rref1 = yield d1
foolscap.ipb.DeadReferenceError: Connection was lost (to tubid=htje) (during method=RIBroker:getReferenceByName)

foolscap.test.test_negotiate.Crossfire.test4
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/build/foolscap-0.13.1/debian/python-foolscap/usr/lib/python2.7/dist-packages/foolscap/banana.py", line 639, in dataReceived
    self.handleData(chunk)
  File "/build/foolscap-0.13.1/debian/python-foolscap/usr/lib/python2.7/dist-packages/foolscap/banana.py", line 739, in handleData
    "but got %r" % s)
foolscap.tokens.BananaError: BananaError(in <RootUnslicer>): ("token prefix is limited to 64 bytes: but got 'banana-decision-version: 1\\r\\nerror: No valid banana-negotiation sequence seen\\r\\n'",)

foolscap.test.test_negotiate.Crossfire.test4
-------------------------------------------------------------------------------
```

foolscap.test.test_info.Connect.testListener also fails but that is just different output and easily fixed:
https://github.com/warner/foolscap/pull/41

```
--- a/src/foolscap/test/test_info.py
+++ b/src/foolscap/test/test_info.py
@@ -146,9 +146,13 @@ class Connect(unittest.TestCase):
         self.assertEqual(ci.connectorStatuses, {})
         (listener, status) = ci.listenerStatus
         self.assertEqual(status, "successful")
-        self.assertEqual(listener,
-                         "Listener on IPv4Address(TCP, '127.0.0.1', %d)"
-                         % self._portnum)
+
+        self.assertTrue(
+            (listener == ("Listener on IPv4Address(TCP, '127.0.0.1', %d)"
+                          % self._portnum)) or
+            (listener == ("Listener on IPv4Address(type='TCP', host='127.0.0.1',"
+                          " port=%d)"
+                          % self._portnum)))
 
     @defer.inlineCallbacks
     def testLoopback(self):
```

**Comment by warner** [comment]
Argh, what a horrible coincidence, I took the Trac bugtracker offline just a week ago because it was getting stuck in some sort of infinite FD-consuming loop (somehow also related to Twisted,but I haven't figured out how yet). Yeah, I fixed this one about the same time.. could you see if https://github.com/warner/foolscap/commit/514813f3968ab57fb16bcd438cbb378397df1788 fixes it for you too?

**Comment by warner** [comment]
Ugh, I remember those Crossfire tests failing, it seemed pretty intermittent, and probably timing related (and you're right, completely unrelated to the trvial Listener format change). I'm not seeing it fail on my laptop now (debian stretch amd64, python2.7.13, twisted-18.9.0), after a dozen loops. Also not seeing it on a debian/sid VPS (python2.7.15, twisted-18.9.0). In the past, I've mostly seen it fail on travis and buildbot automated tests, and to get it to reproduce it locally, I had to run `trial foolscap.test.test_negotiate` in a loop for an hour or so. Very annoying :).

I gotta admit I made some poor choices when writing the foolscap tests, and many (most?) of them use real (localhost/loopback) sockets. The negotiation tests in particular have some hard-coded delays and assume that everything will happen promptly, which of course only works when there's nothing else going on in the system. If I were starting again I'd mock out the reactor and the clock and try to make all those tests fully synchronous.

BTW, the Trac instance is back up now (https://foolscap.lothar.com/trac/). I'm not seeing this one already filed, but I only looked briefly at the list.

**Comment by juliantaylor** [comment]
The test fails everytime for me in debian unstable with the packaged twisted 18.7.0
I have also installed 18.9 with pip in the same environment and it is still failing every time. Is there some optional package that I might be missing?
These are the packages installed during the test into a base buildd system (which is just base + some build tools)
https://salsa.debian.org/python-team/modules/foolscap/blob/no-txtorcon/debian/control#L7

the trac instance does not let me login, I get a blank screen with firefox and a 500 error with chrome.
